blank_issues_enabled: false
contact_links:
  - name: 💬 Discord
    url: https://discord.gg/YKwjt5vuKr
    about: Join our Discord for help and discussions!
  - name: 💼 Slack
    url: https://dub.sh/browserOS-slack
    about: Join our Slack for help and queries!
  - name: 💡 Feature Requests
    url: https://github.com/browseros-ai/BrowserOS/issues/99
    about: Have an idea? Share it here and vote on others
  - name: 📚 Documentation
    url: https://docs.browseros.com/
    about: Find setup guides and learn how to use BrowserOS
